services:
  fastapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - app-network
  streamlit-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: streamlit_frontend
    ports:
      - "8501:8501"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
